aws:
  children:
    docker:
      hosts:
        docker_training:
    nginx:
      hosts:
        docker_training:
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: /home/igor/DevOps/imaximov-a.pem
    ansible_become_user: root    