---
# tasks file for install_docker
  - name: Update the apt package index and install packages to allow apt to use a repository over HTTPS
    ansible.builtin.apt:
      name:
        - apt-transport-https
        - ca-certificates
        - lsb-release
        - gnupg
      state: latest
      update_cache: true

  - name: Create Keyrings directory
    file:
      path: /etc/apt/keyrings
      state: directory
      
  - name: Add Docker official GPG key
    ansible.builtin.apt_key:
      url: "https://download.docker.com/linux/{{ansible_distribution | lower}}/gpg"
      state: present
      keyring: /etc/apt/keyrings/docker.gpg

  - name: Set machine architecture
    set_fact:
      dpkg_arch: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}" 

  - name: Set Up The Repository
    ansible.builtin.apt_repository:
      repo: 'deb [arch={{dpkg_arch}} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ansible_distribution | lower}} {{ ansible_distribution_release }} stable'
      state: present
      filename: docker

  - name: Install Docker
    ansible.builtin.apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
      state: latest
      update_cache: true

  - name: Create the docker group
    ansible.builtin.group:
      name: docker
      state: present

  - name: Add the user admin to docker group
    ansible.builtin.user:
      name: admin
      groups:
        - docker
      append: yes